name: art_generation
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy=1.16.4
  - pip
  - pip:
    - tensorflow>=1.14.0
    - keras>=2.2.4
    - mlflow>=1.2.0
    - scipy==1.1.0
    - matplotlib>=3.1.1
    - pillow>=6.1.0
